apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: envoy
        image: hub.byted.org/security/envoy:v1.27.0
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml"]
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
          readOnly: true
#      - name: backend
#        image: hub.byted.org/security/server_https
#        ports:
#        - containerPort: 443
      - name: backend-http
        image: hub.byted.org/security/server_http
        ports:
          - containerPort: 80
      volumes:
      - name: envoy-config
        configMap:
          name: backend-envoy
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/sockets
          type: Directory
