apiVersion: v1
kind: Service
metadata:
  name: frontend-3
spec:
  ports:
   - port: 3004
     name: http
     protocol: TCP
     targetPort: 3004
  selector:
      app: frontend-3
  type: LoadBalancer
