apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: client-daemonset
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: hub.byted.org/security/client
          args: ["https://backend-envoy:9001"]
      restartPolicy: Always